name: Deploy-Back-Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

   
      - name: Install and Build
        run: |
          cd back-azure
          npm install
          npm test --if-present

    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50242AD57C4A419683D3208F7EAC7377 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EC655B2A2C67439C9C7648AA9ACB945F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5A88E223407B4735A87D5204E2272DE3 }}

      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-azure'
          package: ./back-azure